# Generated by Django 4.2.28 on 2026-02-27 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("provider_customer_id", models.CharField(max_length=255)),
                ("provider_payment_method_id", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("last_four", models.CharField(max_length=4)),
                ("brand", models.CharField(blank=True, max_length=50)),
                ("expiry_month", models.CharField(blank=True, max_length=2)),
                ("expiry_year", models.CharField(blank=True, max_length=4)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_payment_methods",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Tarjeta de Crédito"),
                            ("debit_card", "Tarjeta de Débito"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("mercadopago", "Mercado Pago"),
                            ("oxxo", "OXXO"),
                            ("spei", "SPEI/Transferencia"),
                            ("cash_on_delivery", "Contra Entrega"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("refunded", "Reembolsado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, help_text="Stripe, PayPal, etc.", max_length=50
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("card_last_four", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=50)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago",
                "verbose_name_plural": "pagos",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
