# Generated by Django 4.2.28 on 2026-02-27 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Porcentaje"),
                            ("fixed_amount", "Monto Fijo"),
                            ("free_shipping", "Envío Gratis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje (0-100) o monto fijo",
                        max_digits=10,
                    ),
                ),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("max_uses_per_user", models.PositiveIntegerField(default=1)),
                ("current_uses", models.PositiveIntegerField(default=0)),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicable_brands",
                    models.ManyToManyField(blank=True, to="catalog.brand"),
                ),
                (
                    "applicable_categories",
                    models.ManyToManyField(blank=True, to="catalog.category"),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(blank=True, to="catalog.product"),
                ),
            ],
            options={
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Porcentaje"),
                            ("fixed_amount", "Monto Fijo"),
                            ("free_shipping", "Envío Gratis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "buy_x_get_y",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'buy': 2, 'get': 1, 'discount': 50}",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Mayor número = mayor prioridad"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "applicable_categories",
                    models.ManyToManyField(blank=True, to="catalog.category"),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(blank=True, to="catalog.product"),
                ),
            ],
            options={
                "db_table": "promotions",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="discounts.coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "coupon_usages",
                "unique_together": {("coupon", "order")},
            },
        ),
    ]
