# Generated by Django 4.2.28 on 2026-02-27 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ubicación de inventario",
                "verbose_name_plural": "ubicaciones de inventario",
                "db_table": "inventory_locations",
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "change_qty",
                    models.IntegerField(
                        help_text="Positivo para entrada, negativo para salida"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("purchase", "Compra/Entrada"),
                            ("sale", "Venta/Salida"),
                            ("adjustment", "Ajuste"),
                            ("return", "Devolución"),
                            ("transfer", "Transferencia"),
                            ("reservation", "Reserva"),
                            ("release", "Liberación"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de orden, factura, etc.",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        db_column="location_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.inventorylocation",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de inventario",
                "verbose_name_plural": "movimientos de inventario",
                "db_table": "inventory_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reserved",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        db_column="location_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="inventory.inventorylocation",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventario",
                "verbose_name_plural": "inventarios",
                "db_table": "inventory",
                "unique_together": {("variant", "location")},
            },
        ),
    ]
