# Generated by Django 4.2.28 on 2026-02-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "En Preparación"),
                            ("ready", "Listo para Enviar"),
                            ("shipped", "En Tránsito"),
                            ("in_transit", "En Ruta"),
                            ("out_for_delivery", "En Reparto"),
                            ("delivered", "Entregado"),
                            ("failed", "Entrega Fallida"),
                            ("returned", "Devuelto"),
                        ],
                        default="preparing",
                        max_length=50,
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("fedex", "FedEx"),
                            ("dhl", "DHL"),
                            ("ups", "UPS"),
                            ("redpack", "Redpack"),
                            ("estafeta", "Estafeta"),
                            ("local", "Mensajería Local"),
                            ("internal", "Entrega Propia"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("tracking_url", models.URLField(blank=True)),
                ("shipping_label_url", models.URLField(blank=True)),
                ("shipping_address", models.JSONField(default=dict)),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping_method",
                    models.CharField(default="standard", max_length=100),
                ),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("customer_notes", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "envío",
                "verbose_name_plural": "envíos",
                "db_table": "shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("fedex", "FedEx"),
                            ("dhl", "DHL"),
                            ("ups", "UPS"),
                            ("redpack", "Redpack"),
                            ("estafeta", "Estafeta"),
                            ("local", "Mensajería Local"),
                            ("internal", "Entrega Propia"),
                        ],
                        max_length=50,
                    ),
                ),
                ("method", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="Estado/Provincia", max_length=100
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("postal_code_prefix", models.CharField(blank=True, max_length=10)),
                ("base_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "weight_per_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto mínimo para envío gratis",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("estimated_days_min", models.PositiveIntegerField(default=3)),
                ("estimated_days_max", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "shipping_rates",
                "ordering": ["base_cost"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order_item",
                    models.ForeignKey(
                        db_column="order_item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        db_column="shipment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "shipment_items",
                "unique_together": {("shipment", "order_item")},
            },
        ),
    ]
