# Generated by Django 4.2.28 on 2026-02-27 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("module", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("stack_trace", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "system_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Creación"),
                            ("UPDATE", "Actualización"),
                            ("DELETE", "Eliminación"),
                            ("LOGIN", "Inicio de Sesión"),
                            ("LOGOUT", "Cierre de Sesión"),
                            ("PAYMENT", "Proceso de Pago"),
                            ("REFUND", "Reembolso"),
                            ("SHIP", "Envío"),
                            ("CANCEL", "Cancelación"),
                            ("VIEW", "Visualización"),
                            ("EXPORT", "Exportación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informativo"),
                            ("WARNING", "Advertencia"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Crítico"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                (
                    "entity_type",
                    models.CharField(
                        blank=True, help_text="Modelo afectado", max_length=100
                    ),
                ),
                ("entity_id", models.CharField(blank=True, max_length=100)),
                ("previous_data", models.JSONField(blank=True, default=dict)),
                ("new_data", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_logs_entity__d4c2e5_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_logs_user_id_6193b2_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_logs_action_bcaa71_idx",
                    ),
                ],
            },
        ),
    ]
